---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: ansible-slack-notify-all-instance-18-08
    image: ubuntu/bionic/amd64
  - name: ansible-slack-notify-all-instance-16-04
    image: ubuntu/xenial/amd64
  - name: ansible-slack-notify-all-instance-buster
    image: debian/buster/amd64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: $HOME/.ansible/roles
    ANSIBLE_LOCAL_TEMP: $HOME/.ansible/tmp_df6vb2vfe
    ANSIBLE_REMOTE_TEMP: $HOME/.ansible/tmp_df6vb2vfe
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
